/**
 * `themeon check` (P4.5): три линтера (token-coverage / APCA-contrast / hardcode), выведенные
 * напрямую из найденных багов (§4.10 master) — заменяет заглушку P4.3. `runCheck` — чистая
 * (относительно `opts.cwd`) async-функция без обращений к `process.cwd()`/citty-контексту
 * (тестируемость, тот же паттерн, что `runBuild` P4.4); `checkCommand` — тонкая citty-обёртка,
 * печатающая сгруппированный отчёт и выставляющая exit-код.
 */
import { resolve } from 'node:path'
import { defineCommand } from 'citty'
import { consola } from 'consola'
import { resolveTheme } from '@themeon/core'
import { DEFAULT_THEME_CONFIG_PATH } from '../constants'
import { loadThemeConfig } from '../load-theme'
import { scanSources } from '../checks/scan'
import { checkCoverage } from '../checks/coverage'
import { checkContrastPairs } from '../checks/contrast'
import { checkHardcode } from '../checks/hardcode'
import type { Finding } from '../checks/types'

export interface CheckOptions {
  cwd: string
  config: string
  src?: readonly string[]
  /** Фактический выход `themeon build --out`, исключается из скана (default `tokens.css`, как у `build`). */
  out?: string
  /** Фактический выход `themeon build --tailwind`, исключается из скана, если передан. */
  tailwind?: string
  /** Доп. glob-паттерны, исключённые из скана (Major #23 defense-in-depth #1). */
  ignore?: readonly string[]
  coverage?: boolean
  contrast?: boolean
  hardcode?: boolean
  allowPx?: readonly number[]
  /** `--`-префиксы project-owned/third-party переменных, исключённые из coverage dead-ref (P4.5 code-review MED). */
  coverageIgnorePrefixes?: readonly string[]
}

const DEFAULT_SRC_PATTERNS: readonly string[] = ['**/*.css', '**/*.vue']
const DEFAULT_IGNORE: readonly string[] = ['**/node_modules/**', '**/dist/**', '**/.output/**', '**/.nuxt/**']
const DEFAULT_OUT = 'tokens.css'

/**
 * Content-based skip (Major #23, `findings/P8-css-layers-cli-checks.md` §4.2) — path-independent:
 * ловит сгенерированный файл даже если пользователь не продублировал `--out`/`--tailwind` у
 * `check`. Оба генератора ThemeOn подписывают свой вывод баннером с этим общим регистро-
 * независимым префиксом: `serializeThemeCss` (`@themeon/core`) — `/* generated by @themeon/… *​/`,
 * `tailwindBridge` (`@themeon/tailwind`) — `/* Generated by @themeon/tailwind … *​/`.
 */
const GENERATED_BANNER_RE = /^\s*\/\*\s*generated by @themeon\//i

/**
 * Итоговый ignore-набор скана (defense in depth): дефолты + ФАКТИЧЕСКИЕ пути `--out`/
 * `--tailwind`/`config`, переданные этому же прогону, + произвольные `opts.ignore`.
 * `EXCLUDE_FILE_RE` на имя файла (было в `checks/hardcode.ts`) сюда намеренно не мигрировал —
 * исключения принадлежат сканеру, а не отдельному линтеру (иначе coverage/hardcode снова
 * разойдутся в том, что исключено, Major #23).
 */
function scanIgnorePatterns(opts: CheckOptions): string[] {
  const patterns = [...DEFAULT_IGNORE, opts.out ?? DEFAULT_OUT, opts.config]
  if (opts.tailwind) patterns.push(opts.tailwind)
  if (opts.ignore) patterns.push(...opts.ignore)
  return patterns
}

/**
 * Loads `opts.config`, resolves it through the core resolver, scans `opts.src` (default
 * `**\/*.{css,vue}`) and runs the three enabled linters. `ok` is `false` only when a linter
 * reported a `'error'`-level finding — warnings never flip exit status (Rule 5).
 */
export async function runCheck(opts: CheckOptions): Promise<{ findings: Finding[]; ok: boolean }> {
  const theme = await loadThemeConfig(resolve(opts.cwd, opts.config))
  // Дефолтный `refLayer:'referenced'` эмитит var-chain (`--color-text: var(--color-neutral-900)`)
  // — годится для coverage (имена переменных те же при любом refLayer), но НЕ для APCA: colorjs.io
  // не парсит `var(...)` как цвет. Contrast резолвит ОТДЕЛЬНО с `refLayer:'inline'`, чтобы получить
  // финальные литеральные значения (var-имена/множество A между двумя резолвами идентичны, P-D14).
  const resolved = resolveTheme(theme)
  const resolvedInline = resolveTheme(theme, { refLayer: 'inline' })
  const scanned = await scanSources(opts.cwd, opts.src ?? DEFAULT_SRC_PATTERNS, scanIgnorePatterns(opts))
  const sources = scanned.filter((source) => !GENERATED_BANNER_RE.test(source.content))

  const findings: Finding[] = []
  // Пустой скан — не валидный «зелёный» результат (защита от unused=0/hardcode=0 на пустом
  // входе, findings §4.2 п.3): если сюда дошло 0 файлов, coverage посчитал бы «все токены unused»,
  // а hardcode — «ноль находок», оба выглядели бы как норма, а не как «скан ничего не нашёл».
  if (sources.length === 0) {
    findings.push({ level: 'warning', rule: 'token-coverage', message: 'no sources scanned' })
  }
  if (opts.coverage ?? true)
    findings.push(...checkCoverage(resolved, sources, { ignorePrefixes: opts.coverageIgnorePrefixes }))
  if (opts.contrast ?? true) findings.push(...checkContrastPairs(resolvedInline))
  if (opts.hardcode ?? true) findings.push(...checkHardcode(sources, { allowPx: opts.allowPx }))

  return { findings, ok: findings.every((f) => f.level !== 'error') }
}

function reportFindings(findings: readonly Finding[]): void {
  let errors = 0
  let warnings = 0

  for (const finding of findings) {
    const location = finding.file ? `${finding.file}${finding.line !== undefined ? `:${finding.line}` : ''} — ` : ''
    const line = `[${finding.rule}] ${location}${finding.message}`
    if (finding.level === 'error') {
      errors++
      consola.error(line)
    } else {
      warnings++
      consola.warn(line)
    }
  }

  if (errors === 0 && warnings === 0) consola.success('themeon check: no issues found')
  else consola.info(`themeon check: ${errors} error(s), ${warnings} warning(s)`)
}

export const checkCommand = defineCommand({
  meta: {
    name: 'check',
    description: 'Lint token coverage, APCA contrast and hardcoded values',
  },
  args: {
    config: {
      type: 'string',
      description: 'Path to theme.config.ts',
      default: DEFAULT_THEME_CONFIG_PATH,
    },
    src: {
      type: 'string',
      description: 'Comma-separated glob patterns for source files (default: **/*.css,**/*.vue)',
    },
    out: {
      type: 'string',
      description: 'Actual `themeon build --out` path, excluded from the scan (default tokens.css, same as build)',
      default: DEFAULT_OUT,
    },
    tailwind: {
      type: 'string',
      description: 'Actual `themeon build --tailwind` path, excluded from the scan if passed',
    },
    ignore: {
      type: 'string',
      description: 'Comma-separated extra glob patterns to exclude from the scan',
    },
    coverage: {
      type: 'boolean',
      description: 'Check token coverage (dead/unused var references)',
      default: true,
      negativeDescription: 'Disable the token-coverage check',
    },
    contrast: {
      type: 'boolean',
      description: 'Check APCA contrast of semantic text-on-bg pairs',
      default: true,
      negativeDescription: 'Disable the APCA contrast check',
    },
    hardcode: {
      type: 'boolean',
      description: 'Check for hardcoded hex/px/color-function literals',
      default: true,
      negativeDescription: 'Disable the hardcoded-value check',
    },
    'allow-px': {
      type: 'string',
      description: 'Comma-separated px values to allow (default: 0,1)',
    },
    'coverage-ignore': {
      type: 'string',
      description: 'Comma-separated --var prefixes to exclude from dead-ref coverage errors (project-owned/third-party custom properties)',
    },
  },
  async run({ args }) {
    try {
      const { findings, ok } = await runCheck({
        cwd: process.cwd(),
        config: args.config,
        src: args.src ? args.src.split(',').map((s) => s.trim()) : undefined,
        out: args.out,
        tailwind: args.tailwind,
        ignore: args.ignore ? args.ignore.split(',').map((s) => s.trim()) : undefined,
        coverage: args.coverage,
        contrast: args.contrast,
        hardcode: args.hardcode,
        allowPx: args['allow-px'] ? args['allow-px'].split(',').map(Number) : undefined,
        coverageIgnorePrefixes: args['coverage-ignore']
          ? args['coverage-ignore'].split(',').map((s) => s.trim())
          : undefined,
      })

      reportFindings(findings)
      process.exitCode = ok ? 0 : 1
    } catch (err) {
      consola.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  },
})
