/**
 * `themeon check` (P4.5): три линтера (token-coverage / APCA-contrast / hardcode), выведенные
 * напрямую из найденных багов (§4.10 master) — заменяет заглушку P4.3. `runCheck` — чистая
 * (относительно `opts.cwd`) async-функция без обращений к `process.cwd()`/citty-контексту
 * (тестируемость, тот же паттерн, что `runBuild` P4.4); `checkCommand` — тонкая citty-обёртка,
 * печатающая сгруппированный отчёт и выставляющая exit-код.
 */
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { defineCommand } from 'citty'
import { consola } from 'consola'
import {
  applyThemePatch,
  aggregateDiagnostics,
  diagnosticFromThemeonError,
  diagnosticFromUnknown,
  formatDiagnostics,
  resolveTheme,
  ThemeonError,
} from '@themeon/core'
import type { Diagnostic, TokenTreeInput } from '@themeon/core'
import { checkThemeContrast } from '@themeon/colors'
import { DEFAULT_THEME_CONFIG_PATH } from '../constants'
import { loadThemeConfig } from '../load-theme'
import { scanSources } from '../checks/scan'
import { checkCoverage } from '../checks/coverage'
import { checkContrastPairs } from '../checks/contrast'
import { checkHardcode } from '../checks/hardcode'
import { findingsToDiagnostics } from '../checks/diagnostics'
import type { Finding } from '../checks/types'

export interface CheckResult {
  readonly findings: Finding[]
  readonly diagnostics: readonly Diagnostic[]
  readonly ok: boolean
}

export interface CheckOptions {
  cwd: string
  config: string
  src?: readonly string[]
  /** Фактический выход `themeon build --out`, исключается из скана (default `tokens.css`, как у `build`). */
  out?: string
  /** Фактический выход `themeon build --tailwind`, исключается из скана, если передан. */
  tailwind?: string
  /** Доп. glob-паттерны, исключённые из скана (Major #23 defense-in-depth #1). */
  ignore?: readonly string[]
  coverage?: boolean
  contrast?: boolean
  hardcode?: boolean
  allowPx?: readonly number[]
  /** `--`-префиксы project-owned/third-party переменных, исключённые из coverage dead-ref (P4.5 code-review MED). */
  coverageIgnorePrefixes?: readonly string[]
  /**
   * Путь к JSON-файлу tenant-патча (P6.3, H3 И2) — переключает `runCheck` на fail-closed
   * APCA-гейт публикации ВМЕСТО сканирования coverage/hardcode: base-тема + провалидированный
   * патч (`applyThemePatch`, P6.1) резолвятся в эффективный `lookup`, гоняется
   * `checkThemeContrast` (`@themeon/colors`). Любая ошибка на пути (нечитаемый/невалидный JSON,
   * throw валидации значения, throw парсинга цвета, `pass===false`) — `error`-finding, `ok:false`.
   */
  tenant?: string
}

const DEFAULT_SRC_PATTERNS: readonly string[] = ['**/*.css', '**/*.vue']
const DEFAULT_IGNORE: readonly string[] = ['**/node_modules/**', '**/dist/**', '**/.output/**', '**/.nuxt/**']
const DEFAULT_OUT = 'tokens.css'

/**
 * Content-based skip (Major #23, `findings/P8-css-layers-cli-checks.md` §4.2) — path-independent:
 * ловит сгенерированный файл даже если пользователь не продублировал `--out`/`--tailwind` у
 * `check`. Оба генератора ThemeOn подписывают свой вывод баннером с этим общим регистро-
 * независимым префиксом: `serializeThemeCss` (`@themeon/core`) — `/* generated by @themeon/… *​/`,
 * `tailwindBridge` (`@themeon/tailwind`) — `/* Generated by @themeon/tailwind … *​/`.
 */
const GENERATED_BANNER_RE = /^\s*\/\*\s*generated by @themeon\//i

/**
 * Итоговый ignore-набор скана (defense in depth): дефолты + ФАКТИЧЕСКИЕ пути `--out`/
 * `--tailwind`/`config`, переданные этому же прогону, + произвольные `opts.ignore`.
 * `EXCLUDE_FILE_RE` на имя файла (было в `checks/hardcode.ts`) сюда намеренно не мигрировал —
 * исключения принадлежат сканеру, а не отдельному линтеру (иначе coverage/hardcode снова
 * разойдутся в том, что исключено, Major #23).
 */
function scanIgnorePatterns(opts: CheckOptions): string[] {
  const patterns = [...DEFAULT_IGNORE, opts.out ?? DEFAULT_OUT, opts.config]
  if (opts.tailwind) patterns.push(opts.tailwind)
  if (opts.ignore) patterns.push(...opts.ignore)
  return patterns
}

/**
 * Fail-closed APCA-гейт публикации tenant-темы (P6.3, H3 И2): резолвит base c
 * `refLayer:'inline'` (те же литеральные значения, что и обычный contrast-линтер, Rule про
 * `resolvedInline` в `runCheck`), валидирует `opts.tenant`-патч через `applyThemePatch` (P6.1,
 * ЕДИНСТВЕННЫЙ проход валидации — гейт берёт `.vars`, не ревалидирует), строит эффективный
 * `lookup = {...base.vars, ...patch.vars}` и гоняет `checkThemeContrast` (`@themeon/colors`).
 * ЛЮБОЙ throw на любом из трёх шагов (нечитаемый/невалидный JSON, невалидное значение патча,
 * непарсибельный цвет в APCA) превращается в `error`-finding, НЕ в skip/warning (Implementation
 * Rules item'а — запрещён try/catch, глотающий throw в «пропустить»); `pass===false` — тоже
 * `error`-finding. Три случая суммарно дают fail-closed на ВСЕХ путях H3 И2.
 */
function tenantFailure(finding: Finding, diagnostic: Diagnostic): CheckResult {
  return { findings: [finding], diagnostics: [diagnostic], ok: false }
}

async function runTenantCheck(opts: CheckOptions): Promise<CheckResult> {
  const theme = await loadThemeConfig(resolve(opts.cwd, opts.config))
  const base = resolveTheme(theme, { refLayer: 'inline' })

  let patch: TokenTreeInput
  try {
    const raw = await readFile(resolve(opts.cwd, opts.tenant!), 'utf8')
    patch = JSON.parse(raw) as TokenTreeInput
  } catch (error) {
    const diagnostic = aggregateDiagnostics([
      {
        code: 'THEMEON_PATCH_PARSE',
        severity: 'error',
        message: `tenant patch unreadable or not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
        provenance: { stage: 'tenant', producer: 'runTenantCheck' },
      },
    ])[0]!
    return tenantFailure(
      {
        level: 'error',
        rule: 'contrast',
        code: diagnostic.code,
        message: diagnostic.message,
      },
      diagnostic,
    )
  }

  let vars: Readonly<Record<string, string>>
  try {
    ;({ vars } = applyThemePatch(base, patch))
  } catch (error) {
    const diagnostic =
      error instanceof ThemeonError
        ? diagnosticFromThemeonError(error, { provenance: { stage: 'tenant', producer: 'applyThemePatch' } })
        : diagnosticFromUnknown(error, { provenance: { stage: 'tenant', producer: 'applyThemePatch' } })
    return tenantFailure(
      {
        level: 'error',
        rule: 'contrast',
        code: diagnostic.code,
        message: `tenant patch validation failed: ${diagnostic.message}`,
      },
      diagnostic,
    )
  }

  const lookup: Record<string, string> = { ...base.vars, ...vars }
  try {
    const { pass, wcagReports, reports } = checkThemeContrast(lookup)
    const findings: Finding[] = []
    for (const report of wcagReports) {
      if (report.result.status === 'indeterminate') {
        findings.push({
          level: 'warning',
          rule: 'contrast',
          code: 'THEMEON_CONTRAST_WCAG_INDETERMINATE',
          message: `WCAG indeterminate (${report.result.reason}) for ${report.pair.label}: ${report.result.message}`,
        })
        continue
      }
      if (!report.result.pass) {
        findings.push({
          level: 'error',
          rule: 'contrast',
          code: 'THEMEON_CONTRAST_WCAG_AA',
          message: `WCAG 2.2 AA ${report.result.ratio.toFixed(2)}:1 < ${report.result.threshold}:1 for ${report.pair.label}`,
        })
      }
    }
    for (const report of reports) {
      if (!report.pass) {
        findings.push({
          level: 'warning',
          rule: 'contrast',
          code: 'THEMEON_CONTRAST_APCA_ADVISORY',
          message: `APCA advisory |Lc| ${Math.abs(report.lc).toFixed(1)} < ${report.required} for ${report.pair.label}`,
        })
      }
    }
    return { findings, diagnostics: findingsToDiagnostics(findings), ok: pass }
  } catch (error) {
    const diagnostic = diagnosticFromUnknown(error, {
      provenance: { stage: 'tenant', producer: 'checkThemeContrast' },
    })
    return tenantFailure(
      {
        level: 'error',
        rule: 'contrast',
        code: 'THEMEON_CONTRAST_BAD_COLOR',
        message: `unparseable color pair in effective tenant theme: ${diagnostic.message}`,
      },
      { ...diagnostic, code: 'THEMEON_CONTRAST_BAD_COLOR' },
    )
  }
}

/**
 * Loads `opts.config`, resolves it through the core resolver, scans `opts.src` (default
 * `**\/*.{css,vue}`) and runs the three enabled linters. `ok` is `false` only when a linter
 * reported a `'error'`-level finding — warnings never flip exit status (Rule 5).
 *
 * `opts.tenant` set → delegates entirely to {@link runTenantCheck} (fail-closed APCA
 * publication gate, P6.3): source scanning/coverage/hardcode linters do not apply to a tenant
 * patch publication decision.
 */
export async function runCheck(opts: CheckOptions): Promise<CheckResult> {
  if (opts.tenant !== undefined) return runTenantCheck(opts)

  const theme = await loadThemeConfig(resolve(opts.cwd, opts.config))
  // Дефолтный `refLayer:'referenced'` эмитит var-chain (`--color-text: var(--color-neutral-900)`)
  // — годится для coverage (имена переменных те же при любом refLayer), но НЕ для APCA: colorjs.io
  // не парсит `var(...)` как цвет. Contrast резолвит ОТДЕЛЬНО с `refLayer:'inline'`, чтобы получить
  // финальные литеральные значения (var-имена/множество A между двумя резолвами идентичны, P-D14).
  const resolved = resolveTheme(theme)
  const resolvedInline = resolveTheme(theme, { refLayer: 'inline' })
  const scanned = await scanSources(opts.cwd, opts.src ?? DEFAULT_SRC_PATTERNS, scanIgnorePatterns(opts))
  const sources = scanned.filter((source) => !GENERATED_BANNER_RE.test(source.content))

  const findings: Finding[] = []
  // Пустой скан — не валидный «зелёный» результат (защита от unused=0/hardcode=0 на пустом
  // входе, findings §4.2 п.3): если сюда дошло 0 файлов, coverage посчитал бы «все токены unused»,
  // а hardcode — «ноль находок», оба выглядели бы как норма, а не как «скан ничего не нашёл».
  if (sources.length === 0) {
    findings.push({ level: 'warning', rule: 'token-coverage', message: 'no sources scanned' })
  }
  if (opts.coverage ?? true)
    findings.push(...checkCoverage(resolved, sources, { ignorePrefixes: opts.coverageIgnorePrefixes }))
  if (opts.contrast ?? true) findings.push(...checkContrastPairs(resolvedInline))
  if (opts.hardcode ?? true) findings.push(...checkHardcode(sources, { allowPx: opts.allowPx }))

  return {
    findings,
    diagnostics: findingsToDiagnostics(findings),
    ok: findings.every((f) => f.level !== 'error'),
  }
}

function reportFindings(findings: readonly Finding[]): void {
  const diagnostics = findingsToDiagnostics(findings)
  let errors = 0
  let warnings = 0

  for (const diagnostic of diagnostics) {
    const line = formatDiagnostics([diagnostic], 'plain')
    if (diagnostic.severity === 'error') {
      errors++
      consola.error(line)
    } else {
      warnings++
      consola.warn(line)
    }
  }

  if (errors === 0 && warnings === 0) consola.success('themeon check: no issues found')
  else consola.info(`themeon check: ${errors} error(s), ${warnings} warning(s)`)
}

export const checkCommand = defineCommand({
  meta: {
    name: 'check',
    description: 'Lint token coverage, APCA contrast and hardcoded values',
  },
  args: {
    config: {
      type: 'string',
      description: 'Path to the theme config file',
      default: DEFAULT_THEME_CONFIG_PATH,
    },
    src: {
      type: 'string',
      description: 'Comma-separated glob patterns for source files (default: **/*.css,**/*.vue)',
    },
    out: {
      type: 'string',
      description: 'Actual `themeon build --out` path, excluded from the scan (default tokens.css, same as build)',
      default: DEFAULT_OUT,
    },
    tailwind: {
      type: 'string',
      description: 'Actual `themeon build --tailwind` path, excluded from the scan if passed',
    },
    ignore: {
      type: 'string',
      description: 'Comma-separated extra glob patterns to exclude from the scan',
    },
    coverage: {
      type: 'boolean',
      description: 'Check token coverage (dead/unused var references)',
      default: true,
      negativeDescription: 'Disable the token-coverage check',
    },
    contrast: {
      type: 'boolean',
      description: 'Check APCA contrast of semantic text-on-bg pairs',
      default: true,
      negativeDescription: 'Disable the APCA contrast check',
    },
    hardcode: {
      type: 'boolean',
      description: 'Check for hardcoded hex/px/color-function literals',
      default: true,
      negativeDescription: 'Disable the hardcoded-value check',
    },
    'allow-px': {
      type: 'string',
      description: 'Comma-separated px values to allow (default: 0,1)',
    },
    'coverage-ignore': {
      type: 'string',
      description: 'Comma-separated --var prefixes to exclude from dead-ref coverage errors (project-owned/third-party custom properties)',
    },
    tenant: {
      type: 'string',
      description: 'Path to a tenant patch JSON file — runs the fail-closed APCA publication gate instead of scanning sources',
    },
  },
  async run({ args }) {
    try {
      const { findings, ok } = await runCheck({
        cwd: process.cwd(),
        config: args.config,
        src: args.src ? args.src.split(',').map((s) => s.trim()) : undefined,
        out: args.out,
        tailwind: args.tailwind,
        ignore: args.ignore ? args.ignore.split(',').map((s) => s.trim()) : undefined,
        coverage: args.coverage,
        contrast: args.contrast,
        hardcode: args.hardcode,
        allowPx: args['allow-px'] ? args['allow-px'].split(',').map(Number) : undefined,
        coverageIgnorePrefixes: args['coverage-ignore']
          ? args['coverage-ignore'].split(',').map((s) => s.trim())
          : undefined,
        tenant: args.tenant,
      })

      reportFindings(findings)
      process.exitCode = ok ? 0 : 1
    } catch (err) {
      consola.error(formatDiagnostics([diagnosticFromUnknown(err)], 'pretty'))
      process.exitCode = 1
    }
  },
})
