import { describe, expect, test } from 'vitest'

import { defineTheme, defineTokens } from './define'
import { fromDTCG } from './dtcg/from-dtcg'
import { resolveTheme } from './resolve'
import { serializeThemeCss } from './serialize'
import { isToken } from './types'
import type { Token } from './types'

/** Stable representative theme used by P1.1 characterization (same shape as serialize/parity fixtures). */
function representativeTheme() {
  const palette = defineTokens('color', { forest: { 600: 'oklch(0.55 0.13 155)' } })
  return defineTheme({
    base: {
      color: { bg: { page: 'oklch(0.99 0 0)' }, action: { primary: palette.forest[600] } },
      space: { 4: '1rem' },
      text: { '2xl': { size: '1.5rem', lineHeight: 1.33 } },
      breakpoint: { md: '768px' },
    },
    themes: { dark: { color: { bg: { page: 'oklch(0.15 0 0)' } } } },
  })
}

/** Observed production runtime imports of `@themeon/core` (non-test). Types-only imports are listed in docs. */
const PRODUCTION_RUNTIME_EXPORTS = [
  'ThemeonError',
  'applyTheme',
  'applyThemePatch',
  'clearTheme',
  'defineTheme',
  'defineTokens',
  'diagnosticFromThemeonError',
  'diagnosticFromUnknown',
  'formatDiagnostics',
  'resolveTheme',
  'serializeThemeCss',
  'tenantThemeSchema',
] as const

describe('P1.1 characterization — contracts and ADR set', () => {
  test('public runtime inventory used by production consumers stays exported', async () => {
    const mod = await import('./index')
    const keys = new Set(Object.keys(mod))
    for (const name of PRODUCTION_RUNTIME_EXPORTS) {
      expect(keys.has(name)).toBe(true)
    }
    expect('TOKEN_BRAND' in mod).toBe(false)
  })

  test('observed identity is the path tuple; alias is Token-in-value; trees are frozen', () => {
    const theme = representativeTheme()
    const sys = theme.sys as unknown as {
      color: { bg: { page: Token }; action: { primary: Token } }
    }
    const page = sys.color.bg.page
    const primary = sys.color.action.primary

    expect(isToken(page)).toBe(true)
    expect(page.path).toEqual(['color', 'bg', 'page'])
    expect(JSON.stringify(page.path)).toBe('["color","bg","page"]')
    expect(Object.isFrozen(page)).toBe(true)
    expect(Object.isFrozen(theme)).toBe(true)

    expect(isToken(primary.value)).toBe(true)
    expect((primary.value as Token).path).toEqual(['color', 'forest', '600'])
  })

  test('observed CSS snapshot of the representative theme is byte-stable', () => {
    const css = serializeThemeCss(resolveTheme(representativeTheme(), { aliases: 'legacy-v0' }))
    expect(css).toBe(`/* generated by @themeon/core */
@layer themeon.tokens {
  :root {
    color-scheme: light;
    --color-forest-600: oklch(0.55 0.13 155);
    --breakpoint-md: 768px;
    --color-action-primary: var(--color-forest-600);
    --color-bg-page: oklch(0.99 0 0);
    --spacing-4: 1rem;
    --text-2xl: 1.5rem;
    --text-2xl--line-height: 1.33;
    /* aliases: legacy-v0 (remove after migration) */
    --action-primary: var(--color-action-primary);
    --bg-page: var(--color-bg-page);
    --size-2-xl: var(--text-2xl);
  }
  [data-theme="dark"] {
    color-scheme: dark;
    --color-bg-page: oklch(0.15 0 0);
    /* aliases: legacy-v0 (remove after migration) */
    --bg-page: var(--color-bg-page);
  }
}
@custom-media --bp-md (min-width: 768px);
`)
  })

  test('DTCG normalizer currently drops description metadata (P0.1 gap owned by P1.2 IR)', () => {
    const { definition, diagnostics } = fromDTCG({
      color: {
        $type: 'color',
        bg: {
          page: {
            $value: '#ffffff',
            $description: 'Page background',
          },
        },
      },
    })
    const page = (definition.sys as unknown as { color: { bg: { page: Token } } }).color.bg.page
    expect(page.value).toBe('#ffffff')
    expect(page).not.toHaveProperty('description')
    expect(page).not.toHaveProperty('metadata')
    expect(diagnostics.some((d) => d.message.toLowerCase().includes('description') || d.code.includes('DESCRIPTION'))).toBe(false)
  })
})
