import { describe, expect, test } from 'vitest'
import { defineTheme, defineTokens } from './define'
import { resolveTheme } from './resolve'
import { serializeThemeCss } from './serialize'

/**
 * Расширенный образец из эталона P1.5 Code Guidance: палитра forest.600, sys с ref-ссылкой,
 * dimension, композитный text, breakpoint, легаси-алиасы и патч dark.
 */
function fullTheme() {
  const palette = defineTokens('color', { forest: { 600: 'oklch(0.55 0.13 155)' } })
  return defineTheme({
    base: {
      color: { bg: { page: 'oklch(0.99 0 0)' }, action: { primary: palette.forest[600] } },
      space: { 4: '1rem' },
      text: { '2xl': { size: '1.5rem', lineHeight: 1.33 } },
      breakpoint: { md: '768px' },
    },
    themes: { dark: { color: { bg: { page: 'oklch(0.15 0 0)' } } } },
  })
}

describe('serializeThemeCss — snapshot полного выхода (эталон P1.5)', () => {
  // Отличие от иллюстративного эталона ТЗ: правило legacy-v0 (P1.3) даёт алиас и для
  // text.2xl (--size-2-xl → var(--text-2xl)); эталон эту строку опустил. Сериализатор
  // добросовестно выводит ровно resolved.aliases, поэтому строка присутствует.
  test('байт-в-байт совпадает с эталоном ТЗ', () => {
    const r = resolveTheme(fullTheme(), { aliases: 'legacy-v0' })
    const css = serializeThemeCss(r)
    const expected = `/* generated by @themeon/core */
@layer themeon.tokens {
  :root {
    color-scheme: light;
    --color-forest-600: oklch(0.55 0.13 155);
    --color-bg-page: oklch(0.99 0 0);
    --color-action-primary: var(--color-forest-600);
    --spacing-4: 1rem;
    --text-2xl: 1.5rem;
    --text-2xl--line-height: 1.33;
    --breakpoint-md: 768px;
    /* aliases: legacy-v0 (remove after migration) */
    --bg-page: var(--color-bg-page);
    --action-primary: var(--color-action-primary);
    --size-2-xl: var(--text-2xl);
  }
  [data-theme="dark"] {
    color-scheme: dark;
    --color-bg-page: oklch(0.15 0 0);
  }
}
@custom-media --bp-md (min-width: 768px);
`
    expect(css).toBe(expected)
    // финальный перевод строки обязателен
    expect(css.endsWith('\n')).toBe(true)
  })
})

describe('serializeThemeCss — опции обёртки и at-rules', () => {
  test('layer: false — нет @layer, селекторы на нулевом отступе', () => {
    const r = resolveTheme(fullTheme(), { aliases: 'legacy-v0' })
    const css = serializeThemeCss(r, { layer: false })
    expect(css).not.toContain('@layer')
    // :root теперь top-level, переменные на 2 пробелах
    expect(css).toContain('\n:root {\n')
    expect(css).toContain('\n  --color-bg-page: oklch(0.99 0 0);\n')
    expect(css).toContain('\n[data-theme="dark"] {\n')
  })

  test('emitCustomMedia: false — нет @custom-media', () => {
    const r = resolveTheme(fullTheme(), { aliases: 'legacy-v0' })
    const css = serializeThemeCss(r, { emitCustomMedia: false })
    expect(css).not.toContain('@custom-media')
    // сама переменная брейкпоинта остаётся в :root
    expect(css).toContain('--breakpoint-md: 768px;')
  })

  test('customMediaPrefix и themeAttribute переопределяются', () => {
    const r = resolveTheme(fullTheme())
    const css = serializeThemeCss(r, { customMediaPrefix: 'mq-', themeAttribute: 'data-mode' })
    expect(css).toContain('@custom-media --mq-md (min-width: 768px);')
    expect(css).toContain('[data-mode="dark"] {')
  })

  test('banner: false — без баннера; кастомный баннер эмитится', () => {
    const r = resolveTheme(fullTheme())
    expect(serializeThemeCss(r, { banner: false }).startsWith('@layer')).toBe(true)
    expect(serializeThemeCss(r, { banner: '/* custom */' }).startsWith('/* custom */\n')).toBe(true)
  })
})

describe('serializeThemeCss — @property (emitProperty: color)', () => {
  test('регистрирует цветовые токены базы; initial-value НЕ var()', () => {
    const r = resolveTheme(fullTheme(), { aliases: 'legacy-v0' })
    const css = serializeThemeCss(r, { emitProperty: 'color' })
    // конкретное цветовое значение
    expect(css).toContain(
      '@property --color-bg-page { syntax: "<color>"; inherits: true; initial-value: oklch(0.99 0 0); }',
    )
    // var-chain токен регистрируется финальным значением, а не var()
    expect(css).toContain(
      '@property --color-action-primary { syntax: "<color>"; inherits: true; initial-value: oklch(0.55 0.13 155); }',
    )
    expect(css).not.toContain('initial-value: var(')
    // не-цветовые токены не регистрируются
    expect(css).not.toContain('@property --spacing-4')
    expect(css).not.toContain('@property --text-2xl')
    // @property — вне @layer-блока (top-level)
    expect(css.indexOf('@property')).toBeGreaterThan(css.indexOf('}\n@custom-media'))
  })

  test("emitProperty: 'none' по умолчанию — нет @property", () => {
    const r = resolveTheme(fullTheme())
    expect(serializeThemeCss(r)).not.toContain('@property')
  })
})

describe('serializeThemeCss — color-scheme', () => {
  test('тема без записи в schemes не получает строку color-scheme', () => {
    // тема 'sepia' есть в themes, но нет в schemes (конвенция dark отсутствует)
    const theme = defineTheme({
      base: { color: { bg: { page: '#fff' } } },
      themes: { sepia: { color: { bg: { page: '#f4ecd8' } } } },
    })
    const css = serializeThemeCss(resolveTheme(theme))
    expect(css).toContain('[data-theme="sepia"] {')
    // между открытием блока sepia и переменной не должно быть color-scheme
    const block = css.slice(css.indexOf('[data-theme="sepia"]'))
    expect(block).not.toContain('color-scheme')
    // :root всё равно получает базовую схему light
    expect(css).toContain('color-scheme: light;')
  })

  test('emitColorScheme: false — ни в :root, ни в темах', () => {
    const css = serializeThemeCss(resolveTheme(fullTheme()), { emitColorScheme: false })
    expect(css).not.toContain('color-scheme')
  })

  test("зарезервированный ключ schemes.base переопределяет схему :root", () => {
    const theme = defineTheme({ base: { color: { bg: { page: '#111' } } }, schemes: { base: 'dark' } })
    expect(serializeThemeCss(resolveTheme(theme))).toContain('  :root {\n    color-scheme: dark;')
  })
})

describe('serializeThemeCss — краевые случаи', () => {
  test('пустые themes → нет пустых блоков', () => {
    const theme = defineTheme({ base: { color: { bg: { page: '#fff' } } } })
    const css = serializeThemeCss(resolveTheme(theme))
    expect(css).not.toContain('[data-theme=')
    // нет и висячих пустых блоков
    expect(css).not.toContain('{\n  }')
    expect(css).not.toContain('{\n    }')
  })

  test('нет breakpoints → нет @custom-media', () => {
    const theme = defineTheme({ base: { color: { bg: { page: '#fff' } } } })
    expect(serializeThemeCss(resolveTheme(theme))).not.toContain('@custom-media')
  })

  test('детерминизм: двойной вызов даёт идентичную строку', () => {
    const r = resolveTheme(fullTheme(), { aliases: 'legacy-v0' })
    expect(serializeThemeCss(r)).toBe(serializeThemeCss(r))
  })
})
