/**
 * Сериализатор static CSS (P1.5): `serializeThemeCss` превращает `ResolvedTheme` (P1.4) в
 * детерминированный CSS-текст — build-выход №1 транспорта D4 (анти-FOUC статика в `<head>`).
 *
 * Сериализатор НИЧЕГО не именует и не резолвит сам (P-D14): имена берёт из `resolved.tokens`
 * (порядок обхода) и `resolved.aliases`, значения — из `resolved.vars` (var-chain уже внутри)
 * и `ResolvedToken.value` (блоки тем). Тот же `ResolvedTheme` обязан давать байт-в-байт тот же
 * CSS — это фундамент «пустого diff» пилота P5.
 */

import type { ResolvedTheme } from './types'

/** Опции сериализатора. Все значения по умолчанию воспроизводят канон D6/D8/D14. */
export interface SerializeCssOptions {
  /** Cascade layer name of the wrapper; `false` disables `@layer`. Default `'themeon.tokens'` (D8). */
  layer?: string | false
  /** Selector of the base block. Default `':root'`. */
  selector?: string
  /** Attribute driving theme blocks. Default `'data-theme'` (D6). */
  themeAttribute?: string
  /**
   * Emit `@custom-media --<prefix><name>` for every breakpoint. Default `true` (D14).
   * NOT Baseline: requires `postcss-custom-media` or Lightning CSS at the consumer (R-11 §4).
   */
  emitCustomMedia?: boolean
  /** Prefix of `@custom-media` names. Default `'bp-'`. */
  customMediaPrefix?: string
  /** Emit `color-scheme` in `:root` and theme blocks. Default `true` (D6). */
  emitColorScheme?: boolean
  /**
   * `@property` registration: `'none'` (default) or `'color'` — registers every base color
   * token with `syntax:"<color>"`, `inherits:true` and `initial-value` set to the token's
   * final value (never `var()`). Static-schema / dynamic-values pattern (R-11 §5); required
   * for smoothly animatable theme swaps.
   */
  emitProperty?: 'none' | 'color'
  /** Leading banner comment; `false` omits it. Default `'/* generated by @themeon/core *​/'`. */
  banner?: string | false
}

const DEFAULT_BANNER = '/* generated by @themeon/core */'

/** Собирает блок селектора с заданным отступом: `<indent><selector> {\n<lines>\n<indent>}`. */
function selectorBlock(indent: string, selector: string, lines: readonly string[]): string {
  return `${indent}${selector} {\n${lines.join('\n')}\n${indent}}`
}

/**
 * Serializes a {@link ResolvedTheme} into deterministic static CSS: an optional `@layer`
 * wrapper, the base `:root` block (`color-scheme` + variables + legacy aliases), one
 * `[data-theme="…"]` block per theme patch, and optional top-level `@custom-media` /
 * `@property` at-rules. The same resolved theme always produces byte-for-byte identical
 * output. The function performs no naming and no reference resolution — it reads names and
 * values verbatim from the resolved theme (P-D14).
 *
 * @param resolved output of `resolveTheme`
 * @param opts layer/selector/attribute names and at-rule toggles
 */
export function serializeThemeCss(resolved: ResolvedTheme, opts: SerializeCssOptions = {}): string {
  const {
    layer = 'themeon.tokens',
    selector = ':root',
    themeAttribute = 'data-theme',
    emitCustomMedia = true,
    customMediaPrefix = 'bp-',
    emitColorScheme = true,
    emitProperty = 'none',
    banner = DEFAULT_BANNER,
  } = opts

  const useLayer = layer !== false
  // При наличии @layer селекторы вложены на +2 пробела, их содержимое — на +4.
  const selIndent = useLayer ? '  ' : ''
  const varIndent = useLayer ? '    ' : '  '

  const blocks: string[] = []

  // ── База (:root): color-scheme → токены (порядок resolved.tokens) → легаси-алиасы ──
  const rootLines: string[] = []
  if (emitColorScheme) {
    // Схема базы — зарезервированный ключ 'base'; по умолчанию 'light' (P-D16, P1.2).
    const rootScheme = resolved.schemes['base'] ?? 'light'
    rootLines.push(`${varIndent}color-scheme: ${rootScheme};`)
  }
  for (const token of resolved.tokens) {
    const value = resolved.vars[token.varName] ?? token.value
    rootLines.push(`${varIndent}${token.varName}: ${value};`)
  }
  if (resolved.aliases.length > 0) {
    rootLines.push(`${varIndent}/* aliases: legacy-v0 (remove after migration) */`)
    for (const { alias, target } of resolved.aliases) {
      rootLines.push(`${varIndent}${alias}: var(${target});`)
    }
  }
  blocks.push(selectorBlock(selIndent, selector, rootLines))

  // ── Блоки тем: только патченные переменные (финальные значения) + color-scheme темы ──
  for (const [themeName, tokens] of Object.entries(resolved.themes)) {
    const lines: string[] = []
    if (emitColorScheme) {
      const scheme = resolved.schemes[themeName]
      if (scheme !== undefined) lines.push(`${varIndent}color-scheme: ${scheme};`)
    }
    for (const token of tokens) {
      lines.push(`${varIndent}${token.varName}: ${token.value};`)
    }
    // Пустой патч без своей схемы не даёт пустого блока.
    if (lines.length === 0) continue
    blocks.push(selectorBlock(selIndent, `[${themeAttribute}="${themeName}"]`, lines))
  }

  const out: string[] = []
  if (banner !== false) out.push(banner)
  out.push(useLayer ? `@layer ${layer} {\n${blocks.join('\n')}\n}` : blocks.join('\n'))

  // ── Top-level @custom-media (вне @layer): один канал breakpoints (R-11 §4) ──
  if (emitCustomMedia) {
    for (const [name, bp] of Object.entries(resolved.breakpoints)) {
      out.push(`@custom-media --${customMediaPrefix}${name} (min-width: ${bp.value});`)
    }
  }

  // ── Top-level @property (вне @layer): регистрация цветовых токенов базы (R-11 §5) ──
  if (emitProperty === 'color') {
    for (const token of resolved.tokens) {
      if (token.type !== 'color') continue
      // initial-value — финальное значение токена, НЕ var(): @property его не принимает.
      out.push(
        `@property ${token.varName} { syntax: "<color>"; inherits: true; initial-value: ${token.value}; }`,
      )
    }
  }

  return out.join('\n') + '\n'
}
