import { describe, expect, test } from 'vitest'

import pkg from '../../package.json'
import { defineTheme, defineTokens } from '../define'
import { ThemeonError } from '../errors'
import { TOKEN_BRAND } from '../types'
import { resolveTheme } from '../resolve'
import { serializeThemeCss } from '../serialize'
import { formatCss } from '../formats/css'
import type { TokenType, ThemeDefinition } from '../types'
import {
  COMPILER_STAGES,
  COMPILER_VERSION,
  compileTheme,
  createCompiler,
} from './index'
import type { CompilerExtension, FormatInput } from './types'

function representative() {
  const palette = defineTokens('color', { forest: { 600: 'oklch(0.55 0.13 155)' } })
  return defineTheme({
    base: {
      color: { bg: { page: 'oklch(0.99 0 0)' }, action: { primary: palette.forest[600] } },
      space: { 4: '1rem' },
      text: { '2xl': { size: '1.5rem', lineHeight: 1.33 } },
      breakpoint: { md: '768px' },
    },
    themes: { dark: { color: { bg: { page: 'oklch(0.15 0 0)' } } } },
  })
}

const LEGACY = { aliases: 'legacy-v0' as const }

function transformExt(
  name: string,
  order: number,
  stamp: (resolved: ReturnType<typeof resolveTheme>) => ReturnType<typeof resolveTheme>,
): CompilerExtension {
  return {
    name,
    version: '1.0.0',
    apiVersion: 1,
    stage: 'transform',
    capability: 'transform',
    cacheKey: `cache:${name}`,
    deterministic: true,
    order,
    transform: stamp,
  }
}

describe('staged compiler (P1.5)', () => {
  test('compiler version matches package.json and stages are the declared pipeline', () => {
    expect(COMPILER_VERSION).toBe(pkg.version)
    expect(COMPILER_STAGES).toEqual([
      'normalize',
      'validate',
      'resolve',
      'transform',
      'validate-output',
      'emit',
    ])
  })

  test('compileTheme CSS matches serializeThemeCss(resolveTheme) for the representative fixture', () => {
    const theme = representative()
    const css = compileTheme(theme, { resolve: LEGACY }).css
    expect(css).toBe(serializeThemeCss(resolveTheme(theme, LEGACY)))
  })

  test('the same input is byte-identical across compiles and fingerprints are stable', () => {
    const theme = representative()
    const a = compileTheme(theme, { resolve: LEGACY })
    const b = compileTheme(theme, { resolve: LEGACY })
    expect(a.css).toBe(b.css)
    expect(a.fingerprint).toBe(b.fingerprint)
    expect(a.fingerprint).toMatch(/^[0-9a-f]{16}$/)
  })

  test('explicit serialize defaults share a fingerprint with omitted options', () => {
    const theme = representative()
    const omitted = compileTheme(theme, { resolve: LEGACY })
    const explicit = compileTheme(theme, {
      resolve: LEGACY,
      serialize: {
        layer: 'themeon.tokens',
        selector: ':root',
        themeAttribute: 'data-theme',
        emitCustomMedia: true,
        customMediaPrefix: 'bp-',
        emitColorScheme: true,
        emitProperty: 'none',
        banner: '/* generated by @themeon/core */',
      },
    })
    expect(explicit.fingerprint).toBe(omitted.fingerprint)
    expect(explicit.css).toBe(omitted.css)
  })

  test('fingerprint is sensitive to serialize options, resolve options, IR, and extension cacheKey', () => {
    const theme = representative()
    const base = compileTheme(theme, { resolve: LEGACY }).fingerprint
    expect(compileTheme(theme, { resolve: LEGACY, serialize: { layer: false } }).fingerprint).not.toBe(base)
    expect(compileTheme(theme, { resolve: { ...LEGACY, refLayer: 'inline' } }).fingerprint).not.toBe(base)
    expect(compileTheme(theme, { resolve: { prefix: 'to' } }).fingerprint).not.toBe(base)

    const other = defineTheme({
      base: { color: { bg: { page: 'oklch(0.5 0 0)' } } },
    })
    expect(compileTheme(other).fingerprint).not.toBe(compileTheme(theme).fingerprint)

    const ext = (cacheKey: string): CompilerExtension => ({
      name: 'stamp',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'transform',
      capability: 'transform',
      cacheKey,
      deterministic: true,
      transform: (resolved) => resolved,
    })
    expect(compileTheme(theme, { extensions: [ext('a')] }).fingerprint).not.toBe(
      compileTheme(theme, { extensions: [ext('b')] }).fingerprint,
    )
  })

  test('stage outputs and compiler context are frozen', () => {
    const result = compileTheme(representative(), { resolve: LEGACY })
    expect(Object.isFrozen(result)).toBe(true)
    expect(Object.isFrozen(result.document)).toBe(true)
    expect(Object.isFrozen(result.resolved)).toBe(true)
    expect(Object.isFrozen(result.resolved.vars)).toBe(true)
    expect(Object.isFrozen(result.artifacts)).toBe(true)
    expect(Object.isFrozen(result.context)).toBe(true)
    expect(Object.isFrozen(result.context.extensions)).toBe(true)
    expect(Object.isFrozen(result.diagnostics)).toBe(true)
  })

  test('pipeline diagnostics are structured objects, not formatted strings', () => {
    const result = compileTheme(representative(), { resolve: LEGACY })
    expect(Array.isArray(result.diagnostics)).toBe(true)
    for (const diagnostic of result.diagnostics) {
      expect(diagnostic).toEqual(expect.objectContaining({ code: expect.any(String), severity: expect.any(String) }))
      expect(typeof diagnostic).toBe('object')
    }
  })
})

describe('instance-scoped extensions', () => {
  test('two compiler instances do not share extensions', () => {
    const theme = representative()
    const stamp: CompilerExtension = {
      name: 'stamp',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'transform',
      capability: 'transform',
      cacheKey: 'cache:stamp',
      deterministic: true,
      transform(resolved) {
        return {
          ...resolved,
          vars: Object.freeze({ ...resolved.vars, '--stamp': '1' }),
        }
      },
    }
    const stamped = createCompiler({ resolve: LEGACY, extensions: [stamp] })
    const plain = createCompiler({ resolve: LEGACY })
    expect(stamped.compile(theme).resolved.vars['--stamp']).toBe('1')
    expect(plain.compile(theme).resolved.vars['--stamp']).toBeUndefined()
    expect(plain.compile(theme).css).toBe(serializeThemeCss(resolveTheme(theme, LEGACY)))
  })

  test('duplicate stage+capability+name is a collision, including against builtins', () => {
    const dup: CompilerExtension = {
      name: 'css',
      version: '9.0.0',
      apiVersion: 1,
      stage: 'emit',
      capability: 'format',
      cacheKey: 'other',
      deterministic: true,
      format: () => 'stolen { }\n',
    }
    expect(() => createCompiler({ extensions: [dup] })).toThrow(ThemeonError)
    try {
      createCompiler({ extensions: [dup] })
    } catch (error) {
      expect((error as ThemeonError).code).toBe('EXTENSION_COLLISION')
    }

    const user: CompilerExtension = {
      name: 'twice',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'transform',
      capability: 'transform',
      cacheKey: 'cache:twice',
      deterministic: true,
      transform: (resolved) => resolved,
    }
    expect(() => createCompiler({ extensions: [user, { ...user, cacheKey: 'other' }] })).toThrow(
      /Duplicate extension "twice"/,
    )
  })

  test('missing or blank cacheKey is rejected', () => {
    const missing = {
      name: 'ghost',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'transform',
      capability: 'transform',
      cacheKey: '   ',
      deterministic: true,
      transform: (resolved: ReturnType<typeof resolveTheme>) => resolved,
    } satisfies CompilerExtension
    expect(() => createCompiler({ extensions: [missing] })).toThrow(ThemeonError)
    try {
      createCompiler({ extensions: [missing] })
    } catch (error) {
      expect((error as ThemeonError).code).toBe('EXTENSION_CACHE')
    }
  })

  test('custom alias function without aliasesCacheKey is a missing cache contribution', () => {
    const theme = representative()
    expect(() =>
      compileTheme(theme, {
        resolve: { aliases: () => null },
      }),
    ).toThrow(/aliasesCacheKey/)
    const withKey = compileTheme(theme, {
      resolve: { aliases: () => null },
      aliasesCacheKey: 'alias:none',
    })
    const otherKey = compileTheme(theme, {
      resolve: { aliases: () => null },
      aliasesCacheKey: 'alias:other',
    })
    expect(withKey.fingerprint).not.toBe(otherKey.fingerprint)
  })

  test('resolve stage is not an extension point', () => {
    const ext = {
      name: 'hijack-resolve',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'resolve',
      capability: 'transform',
      cacheKey: 'cache:resolve',
      deterministic: true,
      transform: (resolved: ReturnType<typeof resolveTheme>) => resolved,
    } as unknown as CompilerExtension
    expect(() => createCompiler({ extensions: [ext] })).toThrow(/Unknown compiler stage/)
  })

  test('async extensions are rejected (sync-first)', () => {
    const asyncExt: CompilerExtension = {
      name: 'net',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'transform',
      capability: 'transform',
      cacheKey: 'cache:net',
      deterministic: true,
      async: true,
      transform: (resolved) => resolved,
    }
    expect(() => createCompiler({ extensions: [asyncExt] })).toThrow(ThemeonError)
    try {
      createCompiler({ extensions: [asyncExt] })
    } catch (error) {
      expect((error as ThemeonError).code).toBe('EXTENSION_ASYNC')
    }
  })

  test('declared order is deterministic regardless of registration permutation', () => {
    const theme = representative()
    const a = transformExt('a', 1, (resolved) => ({
      ...resolved,
      vars: Object.freeze({ ...resolved.vars, '--order': `${resolved.vars['--order'] ?? ''}a` }),
    }))
    const b = transformExt('b', 2, (resolved) => ({
      ...resolved,
      vars: Object.freeze({ ...resolved.vars, '--order': `${resolved.vars['--order'] ?? ''}b` }),
    }))
    const ab = createCompiler({ resolve: LEGACY, extensions: [a, b] }).compile(theme)
    const ba = createCompiler({ resolve: LEGACY, extensions: [b, a] }).compile(theme)
    expect(ab.resolved.vars['--order']).toBe('ab')
    expect(ba.resolved.vars['--order']).toBe('ab')
    expect(ab.fingerprint).toBe(ba.fingerprint)
    expect(ab.context.extensions.filter((ext) => ext.name === 'a' || ext.name === 'b').map((ext) => ext.name)).toEqual([
      'a',
      'b',
    ])
  })
})

describe('formats cannot resolve', () => {
  test('built-in css format is serializeThemeCss over resolved output', () => {
    const resolved = resolveTheme(representative(), LEGACY)
    expect(formatCss({ resolved, options: {} })).toBe(serializeThemeCss(resolved))
  })

  test('format hooks receive resolved output only', () => {
    const theme = representative()
    let seen: FormatInput | undefined
    const spy: CompilerExtension = {
      name: 'spy',
      version: '1.0.0',
      apiVersion: 1,
      stage: 'emit',
      capability: 'format',
      cacheKey: 'cache:spy',
      deterministic: true,
      format(input) {
        seen = input
        return '/* spy */\n'
      },
    }
    const result = compileTheme(theme, { resolve: LEGACY, extensions: [spy] })
    expect(seen).toBeDefined()
    expect(seen).not.toHaveProperty('theme')
    expect(seen).not.toHaveProperty('definition')
    expect(seen).not.toHaveProperty('document')
    expect(seen?.resolved).toBe(result.resolved)
    expect(result.artifacts.spy).toBe('/* spy */\n')
    expect(result.artifacts.css).toBe(result.css)
  })
})

describe('compiler failure parity', () => {
  function rawToken(path: string[]): {
    [TOKEN_BRAND]: true
    type: TokenType
    path: string[]
    value: unknown
  } {
    return { [TOKEN_BRAND]: true, type: 'color', path, value: null }
  }

  test('cycles still throw ThemeonError CYCLE', () => {
    const a = rawToken(['color', 'a'])
    const b = rawToken(['color', 'b'])
    a.value = b
    b.value = a
    const def = { sys: { color: { a, b } }, themes: {}, schemes: {} } as unknown as ThemeDefinition
    expect(() => compileTheme(def)).toThrow(ThemeonError)
    try {
      compileTheme(def)
    } catch (error) {
      expect((error as ThemeonError).code).toBe('CYCLE')
    }
  })
})
