import { normalizeDsl } from '../authoring/normalize-dsl'
import { aggregateDiagnostics } from '../diagnostics/aggregate'
import { diagnosticsFromGraphIssues } from '../diagnostics/from-legacy'
import type { Diagnostic } from '../diagnostics/types'
import { ThemeonError } from '../errors'
import { GRAPH_MAX_DEPTH, buildGraph } from '../graph/build'
import { toThemeDefinition } from '../model/to-definition'
import { resolveTheme } from '../resolve'
import type { ResolveOptions } from '../resolve'
import type { SerializeCssOptions } from '../serialize'
import type { ResolvedTheme, ThemeDefinition } from '../types'
import { declareExtensions } from './extensions'
import { buildFingerprint } from './fingerprint'
import type {
  Compiler,
  CompilerContext,
  CompilerExtension,
  CompilerOptions,
  CompilerStage,
  CompileResult,
  FormatInput,
} from './types'
import { COMPILER_STAGES, COMPILER_VERSION } from './types'

const DEFAULT_BANNER = '/* generated by @themeon/core */'

function resolveSerializeOptions(opts: SerializeCssOptions = {}): CompilerContext['serialize'] {
  return Object.freeze({
    layer: opts.layer === undefined ? 'themeon.tokens' : opts.layer,
    selector: opts.selector ?? ':root',
    themeAttribute: opts.themeAttribute ?? 'data-theme',
    emitCustomMedia: opts.emitCustomMedia ?? true,
    customMediaPrefix: opts.customMediaPrefix ?? 'bp-',
    emitColorScheme: opts.emitColorScheme ?? true,
    emitProperty: opts.emitProperty ?? 'none',
    banner: opts.banner === undefined ? DEFAULT_BANNER : opts.banner,
  })
}

function aliasesContribution(
  aliases: ResolveOptions['aliases'],
  aliasesCacheKey: string | undefined,
): { aliases: 'legacy-v0' | 'custom' | undefined; aliasesCacheKey?: string } {
  if (aliases === undefined) return { aliases: undefined }
  if (aliases === 'legacy-v0') return { aliases: 'legacy-v0' }
  const key = aliasesCacheKey?.trim() ?? ''
  if (key === '') {
    throw new ThemeonError(
      'EXTENSION_CACHE',
      'Custom alias rule is missing aliasesCacheKey cache contribution',
    )
  }
  return { aliases: 'custom', aliasesCacheKey: key }
}

function freezeResolved(resolved: ResolvedTheme): ResolvedTheme {
  const themes: Record<string, ResolvedTheme['themes'][string]> = {}
  for (const [name, tokens] of Object.entries(resolved.themes)) {
    themes[name] = Object.freeze([...tokens])
  }
  return Object.freeze({
    tokens: Object.freeze([...resolved.tokens]),
    themes: Object.freeze(themes),
    aliases: Object.freeze([...resolved.aliases]),
    breakpoints: Object.freeze({ ...resolved.breakpoints }),
    vars: Object.freeze({ ...resolved.vars }),
    schemes: Object.freeze({ ...resolved.schemes }),
  })
}

function atStage(runtime: readonly CompilerExtension[], stage: CompilerStage): CompilerExtension[] {
  return runtime.filter((ext) => ext.stage === stage)
}

function throwGraphFailure(issues: ReturnType<typeof buildGraph>['issues']): void {
  const depth = issues.find((issue) => issue.code === 'DEPTH')
  if (depth) {
    throw new ThemeonError(
      'CYCLE',
      `Token reference chain exceeds GRAPH_MAX_DEPTH (${GRAPH_MAX_DEPTH}) at ${depth.from}`,
    )
  }
  const missing = issues.find((issue) => issue.code === 'MISSING_REF')
  if (missing) {
    throw new ThemeonError(
      'UNKNOWN_PATH',
      `Missing token reference: ${missing.ref.join('.')}`,
      { path: missing.ref },
    )
  }
  const cycle = issues.find((issue) => issue.code === 'CYCLE')
  if (cycle) {
    throw new ThemeonError(
      'CYCLE',
      `Circular token reference: ${cycle.paths.map((path) => path.join('.')).join(' → ')}`,
      cycle.paths[0] !== undefined ? { path: cycle.paths[0] } : {},
    )
  }
}

/**
 * Instance-scoped compiler. Extensions registered here never leak into another instance.
 * Stage hooks are explicit functions, not generic middleware.
 */
export function createCompiler(options: CompilerOptions = {}): Compiler {
  const { declared, runtime } = declareExtensions(options.extensions ?? [])
  const serialize = resolveSerializeOptions(options.serialize)
  const resolveOpts = options.resolve ?? {}
  const aliases = aliasesContribution(resolveOpts.aliases, options.aliasesCacheKey)
  const context: CompilerContext = Object.freeze({
    compilerVersion: COMPILER_VERSION,
    stages: COMPILER_STAGES,
    resolve: Object.freeze({
      ...(resolveOpts.prefix !== undefined ? { prefix: resolveOpts.prefix } : {}),
      refLayer: resolveOpts.refLayer ?? 'referenced',
      aliases: aliases.aliases,
      ...(aliases.aliasesCacheKey !== undefined ? { aliasesCacheKey: aliases.aliasesCacheKey } : {}),
    }),
    serialize,
    extensions: declared,
  })

  return Object.freeze({
    context,
    compile(theme: ThemeDefinition): CompileResult {
      const diagnostics: Diagnostic[] = []

      // 1. normalize
      let document = normalizeDsl(theme)
      for (const ext of atStage(runtime, 'normalize')) {
        document = Object.freeze(ext.normalize!(document))
      }

      // 2. validate
      const graph = buildGraph(document)
      diagnostics.push(...diagnosticsFromGraphIssues(graph.issues))
      for (const ext of atStage(runtime, 'validate')) {
        diagnostics.push(...ext.validate!({ document }))
      }
      throwGraphFailure(graph.issues)

      // 3. resolve — round-trip IR so normalizer extensions affect evaluation
      const resolved = freezeResolved(resolveTheme(toThemeDefinition(document), resolveOpts))

      // 4. transform
      let transformed = resolved
      for (const ext of atStage(runtime, 'transform')) {
        transformed = freezeResolved(ext.transform!(transformed, document))
      }

      // 5. validate-output
      for (const ext of atStage(runtime, 'validate-output')) {
        diagnostics.push(...ext.validate!({ document, resolved: transformed }))
      }

      // 6. emit — formats never receive ThemeDefinition / IR
      const artifacts: Record<string, string> = {}
      const formatInput: FormatInput = Object.freeze({ resolved: transformed, options: serialize })
      for (const ext of atStage(runtime, 'emit')) {
        artifacts[ext.name] = ext.format!(formatInput)
      }

      const css = artifacts.css
      if (typeof css !== 'string') {
        throw new ThemeonError('BAD_VALUE', 'Built-in css format did not emit a string artifact')
      }

      return Object.freeze({
        document,
        resolved: transformed,
        css,
        artifacts: Object.freeze({ ...artifacts }),
        fingerprint: buildFingerprint(document, context),
        diagnostics: aggregateDiagnostics(diagnostics),
        context,
      })
    },
  })
}

export function compileTheme(theme: ThemeDefinition, options?: CompilerOptions): CompileResult {
  return createCompiler(options).compile(theme)
}
