/**
 * `tailwindBridge` (P4.1, форма — P8.3) — единственный генератор Tailwind v4-моста.
 *
 * Ничего не именует заново: имена переменных берутся готовыми из `ResolvedTheme`
 * (naming engine ядра применяется один раз — P-D14). Здесь только фильтрация по
 * Tailwind-namespace и построение `@theme reference`-блока с литеральными значениями
 * (P-D54, supersedes P-D31): Tailwind при `reference` НИКОГДА не эмитит переменные
 * ThemeOn в `:root, :host` (исходники 4.3.2, `findings/P8-tailwind-bridge-form.md` §1) —
 * порядка подключения CSS относительно этого моста больше не существует как проблемы.
 * `@theme inline`/обычный `@theme`/`@theme static` здесь запрещены: self-referential
 * `inline`-форма (бывший P-D31) при обратном порядке `@import` даёт цикл
 * `--x: var(--x)` (Blocker #5), а `--breakpoint-*` внутри неё уходит в `@media` как
 * `var(...)`, что невалидно в media-условии (Blocker #4).
 */

import type { CssVarName, ResolvedTheme } from '@themeon/core'
import { TAILWIND_NAMESPACES } from './namespaces'

export interface TailwindBridgeOptions {
  /** 'all' = base tokens ∪ all theme patches (union of names); 'base' = only base. Default 'all'. */
  include?: 'all' | 'base'
  /** Restrict emitted namespaces (subset of TAILWIND_NAMESPACES). Default: all of them. */
  namespaces?: readonly string[]
  /** Emit leading "generated" banner comment. Default true. */
  banner?: boolean
}

const BANNER = '/* Generated by @themeon/tailwind — do not edit. */'

/**
 * Namespace'ы, чьё значение Tailwind разбирает на этапе сборки (тени — `--tw-shadow-color`
 * для модификаторов вида `shadow-black/25`) → литерал запекает семантику навсегда и
 * dark-своп теней до утилиты не доходит; значение обязано остаться `var()`-ссылкой
 * (эмпирика 4.3.2, findings §3 — единственное исключение из «литерал»).
 */
const VALUE_PARSED_NAMESPACES = new Set(['shadow'])

/**
 * Namespace, чьё значение Tailwind подставляет СТРОКОЙ в `@media (width >= …)`
 * (`variants.ts`) — `var()` там невалиден по спеке CSS (не значение свойства) и правило
 * молча отбрасывается браузером (Blocker #4). Литерал обязателен независимо от формы
 * остального моста.
 */
const LITERAL_ONLY_NAMESPACES = new Set(['breakpoint'])

/**
 * Namespace'ы отсортированные по убыванию длины — матчинг по самому длинному префиксу
 * (Rule 3, `phases/P4.md` P4.1): `--font-weight-bold` обязан уйти в `font-weight`, а не в
 * `font` (иначе Tailwind получит мусорную переменную вне своего `font-weight`-namespace).
 */
function sortByLengthDesc(namespaces: readonly string[]): string[] {
  return [...namespaces].sort((a, b) => b.length - a.length)
}

/** Находит namespace ThemeOn-переменной по самому длинному совпадающему префиксу. */
export function matchNamespace(
  varName: CssVarName,
  namespaces: readonly string[] = TAILWIND_NAMESPACES,
): string | null {
  const sorted = sortByLengthDesc(namespaces)
  for (const ns of sorted) {
    if (varName === `--${ns}` || varName.startsWith(`--${ns}-`)) return ns
  }
  return null
}

/**
 * Собирает varName→литерал из резолвленной темы: всегда база (`resolved.tokens`,
 * `ResolvedToken.value` — цепочки ссылок уже схлопнуты резолвером), плюс при
 * `include !== 'base'` — патчи тем для имён, которых нет в базе (тема может вводить var,
 * отсутствующий в base; Rule 4 findings §4п5). Значение НЕ берётся из `resolved.vars` —
 * там для var-chain токенов лежит `var(--другое-имя)` (P-D13), а не литерал; подстановка
 * такой ссылки в `@theme reference` дала бы висячую ссылку на переменную, которую этот
 * же мост не эмитит.
 */
function collectVarLiterals(resolved: ResolvedTheme, include: 'all' | 'base'): Map<CssVarName, string> {
  const literals = new Map<CssVarName, string>()
  for (const tok of resolved.tokens) literals.set(tok.varName, tok.value)
  if (include !== 'base') {
    for (const patch of Object.values(resolved.themes)) {
      for (const tok of patch) if (!literals.has(tok.varName)) literals.set(tok.varName, tok.value)
    }
  }
  return literals
}

/**
 * Generate a Tailwind v4 `@theme reference` bridge from a resolved ThemeOn theme.
 * Every ThemeOn var whose namespace is Tailwind-recognised gets a literal value (except
 * `shadow-*`, kept as a `var()` reference, and `breakpoint-*`, always literal) — `reference`
 * never emits the variable into `:root, :host`, so runtime `[data-theme]` swaps from
 * `tokens.css` reach the generated utilities via their `var(--x, <literal>)` fallback slot,
 * with no dependency on CSS import order (P-D54, supersedes P-D31).
 */
export function tailwindBridge(resolved: ResolvedTheme, opts?: TailwindBridgeOptions): string {
  const include = opts?.include ?? 'all'
  const namespaces = opts?.namespaces ?? TAILWIND_NAMESPACES
  const banner = opts?.banner ?? true

  const literals = collectVarLiterals(resolved, include)
  const filtered = [...literals.keys()].filter((name) => matchNamespace(name, namespaces) !== null)
  filtered.sort()

  const lines = filtered.map((name) => {
    const ns = matchNamespace(name, namespaces)!
    if (LITERAL_ONLY_NAMESPACES.has(ns)) return `  ${name}: ${literals.get(name)};`
    if (VALUE_PARSED_NAMESPACES.has(ns)) return `  ${name}: var(${name});`
    return `  ${name}: ${literals.get(name)};`
  })
  const body = `@theme reference {\n${lines.join('\n')}${lines.length > 0 ? '\n' : ''}}\n`

  return banner ? `${BANNER}\n${body}` : body
}
