/**
 * `tailwindBridge` (P4.1) — единственный генератор Tailwind v4 `@theme inline`-моста.
 *
 * Ничего не именует заново: имена переменных берутся готовыми из `ResolvedTheme`
 * (naming engine ядра применяется один раз — P-D14). Здесь только фильтрация по
 * Tailwind-namespace и построение self-referential mapping (P-D31): `@theme inline`
 * обязателен, non-inline `@theme` здесь не эмитится никогда — non-inline создаёт
 * глобальную `:root`-переменную, чья подстановка не переопределяется под
 * `[data-theme=dark]`, и тёмная тема ломается (R-14 §2.1).
 */

import type { CssVarName, ResolvedTheme } from '@themeon/core'
import { TAILWIND_NAMESPACES } from './namespaces'

export interface TailwindBridgeOptions {
  /** 'all' = base tokens ∪ all theme patches (union of names); 'base' = only base. Default 'all'. */
  include?: 'all' | 'base'
  /** Restrict emitted namespaces (subset of TAILWIND_NAMESPACES). Default: all of them. */
  namespaces?: readonly string[]
  /** Emit leading "generated" banner comment. Default true. */
  banner?: boolean
}

const BANNER = '/* Generated by @themeon/tailwind — do not edit. */'

/**
 * Namespace'ы отсортированные по убыванию длины — матчинг по самому длинному префиксу
 * (Rule 3, `phases/P4.md` P4.1): `--font-weight-bold` обязан уйти в `font-weight`, а не в
 * `font` (иначе Tailwind получит мусорную переменную вне своего `font-weight`-namespace).
 */
function sortByLengthDesc(namespaces: readonly string[]): string[] {
  return [...namespaces].sort((a, b) => b.length - a.length)
}

/** Находит namespace ThemeOn-переменной по самому длинному совпадающему префиксу. */
export function matchNamespace(
  varName: CssVarName,
  namespaces: readonly string[] = TAILWIND_NAMESPACES,
): string | null {
  const sorted = sortByLengthDesc(namespaces)
  for (const ns of sorted) {
    if (varName === `--${ns}` || varName.startsWith(`--${ns}-`)) return ns
  }
  return null
}

/**
 * Собирает уникальные имена переменных из резолвленной темы: всегда база
 * (`resolved.tokens`), плюс при `include !== 'base'` — все патчи тем (тема может
 * вводить var, которого нет в базе).
 */
function collectVarNames(resolved: ResolvedTheme, include: 'all' | 'base'): Set<CssVarName> {
  const names = new Set<CssVarName>()
  for (const tok of resolved.tokens) names.add(tok.varName)
  if (include !== 'base') {
    for (const patch of Object.values(resolved.themes)) {
      for (const tok of patch) names.add(tok.varName)
    }
  }
  return names
}

/**
 * Generate a Tailwind v4 `@theme inline` bridge from a resolved ThemeOn theme.
 * Every ThemeOn var whose namespace is Tailwind-recognised becomes a self-referential
 * mapping `--x: var(--x);`, so Tailwind emits utilities that inline `var(--x)` — runtime
 * `[data-theme]` swaps then reach the utilities without a rebuild (P-D31).
 */
export function tailwindBridge(resolved: ResolvedTheme, opts?: TailwindBridgeOptions): string {
  const include = opts?.include ?? 'all'
  const namespaces = opts?.namespaces ?? TAILWIND_NAMESPACES
  const banner = opts?.banner ?? true

  const names = collectVarNames(resolved, include)
  const filtered = [...names].filter((name) => matchNamespace(name, namespaces) !== null)
  filtered.sort()

  const lines = filtered.map((name) => `  ${name}: var(${name});`)
  const body = `@theme inline {\n${lines.join('\n')}${lines.length > 0 ? '\n' : ''}}\n`

  return banner ? `${BANNER}\n${body}` : body
}
