import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'
import { defineTheme } from '@themeon/core'
import { runCheck } from './commands/check'
import { loadThemeConfig } from './load-theme'

// Keep the config-loading seam explicit so the command and its tokens share one module graph.
vi.mock('./load-theme', () => ({ loadThemeConfig: vi.fn() }))

describe('check command security boundary', () => {
  let cwd: string
  beforeEach(() => {
    cwd = mkdtempSync(join(tmpdir(), 'themeon-check-security-'))
    vi.mocked(loadThemeConfig).mockResolvedValue(defineTheme({ base: { color: { a: 'red' } } }))
  })
  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true })
    vi.resetAllMocks()
  })

  test('hostile authoring values fail before scanning sources', async () => {
    vi.mocked(loadThemeConfig).mockResolvedValue(defineTheme({ base: { gradient: {
      a: 'url(a" ); color:red; } body { display:none } /* ")',
    } } }))
    await expect(runCheck({ cwd, config: 'theme.config.ts' })).rejects.toMatchObject({ code: 'UNSAFE_CSS_TOKEN' })
  })

  test('generated CSS is excluded while real sources retain coverage checking', async () => {
    writeFileSync(join(cwd, 'app.css'), '.x { color: var(--color-a); }')
    writeFileSync(join(cwd, 'other-generated.css'), '/* generated by @themeon/core */ .x { color: var(--unknown); }')
    const result = await runCheck({ cwd, config: 'theme.config.ts', contrast: false, hardcode: false })
    expect(result.ok).toBe(true)
    expect(result.findings.some((finding) => finding.level === 'error')).toBe(false)
  })

  test('hostile tenant values produce a failed check', async () => {
    writeFileSync(join(cwd, 'patch.json'), JSON.stringify({ color: { a: 'red; color:blue' } }))
    const result = await runCheck({ cwd, config: 'theme.config.ts', tenant: 'patch.json' })
    expect(result.ok).toBe(false)
    expect(result.diagnostics.some((diagnostic) => diagnostic.severity === 'error')).toBe(true)
  })
})
